# Generated by Django 4.0.2 on 2022-04-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembukuan_kas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='Tanggal_Transaksi',
            field=models.DateField(),
        ),
    ]
